import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';

export const TermsPage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#0f111a] text-gray-300 font-sans p-6 md:p-12">
      <div className="max-w-4xl mx-auto">
        <button 
          onClick={() => navigate(-1)} 
          className="flex items-center gap-2 text-sm text-indigo-400 hover:text-indigo-300 mb-8 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back
        </button>

        <div className="flex items-center gap-3 mb-8">
            <div className="p-3 bg-indigo-500/10 rounded-xl">
                <FileText className="w-6 h-6 text-indigo-500" />
            </div>
            <h1 className="text-3xl font-bold text-white">Terms of Use</h1>
        </div>

        <div className="space-y-8 text-sm leading-relaxed bg-gray-900/50 p-8 rounded-2xl border border-gray-800">
          <section>
            <h2 className="text-lg font-bold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By accessing and using Cytyos ("the Platform"), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use our services.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">2. Nature of Services (AI Disclaimer)</h2>
            <p className="text-gray-400">
              Cytyos is a decision support tool that uses Artificial Intelligence and geospatial data to provide urban analysis. <strong>The Platform does not provide professional architectural, engineering, legal, or financial advice.</strong>
            </p>
            <p className="mt-2 text-gray-400">
              Results generated by the AI (including zoning analysis, financial feasibility, and massing models) are estimates only and may contain errors. You should always verify all data with local authorities and qualified professionals before making any investment or construction decisions.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">3. User License</h2>
            <p>We grant you a limited, non-exclusive, non-transferable license to use the Platform for your internal business purposes. You agree not to reverse engineer, copy, or resell the Platform's data or functionality.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">4. Subscriptions and Payments</h2>
            <p>Certain features require a paid subscription. Payments are processed securely via third-party providers (Stripe). Subscriptions automatically renew unless cancelled. Refunds are handled on a case-by-case basis at our sole discretion.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">5. Limitation of Liability</h2>
            <p className="uppercase font-bold text-xs text-gray-500 mb-1">Important:</p>
            <p>To the maximum extent permitted by law, Cytyos shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service, including but not limited to loss of profits, data, or investment opportunities.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mb-2">6. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Platform constitutes acceptance of updated terms.</p>
          </section>

          <div className="pt-8 border-t border-gray-800 text-xs text-gray-500">
            Last updated: January 2026. Contact: support@cytyos.com
          </div>
        </div>
      </div>
    </div>
  );
};